version: 2

updates:
  - package-ecosystem: "cargo"
    directory: "/sdd"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "update"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
