ignore:
  - "asg/**"
  - "process/**"
  - "sdd/**"
  - "**.rs"
  - "spec/**"
  - "docs/*"
  - "docs/**/nav-*.adoc"

comment:
  layout: "header, diff, flags, components"  # show component info in the PR comment
  
component_management:
  default_rules:  # default rules that will be inherited by all components
    statuses:
      - type: project # in this case every component that doens't have a status defined will have a project type one
        target: auto
        branches:
          - "!main"
  individual_components:
    - component_id: spec  # this is an identifier that should not be changed
      name: Spec coverage  # this is a display name, and can be changed freely
      paths:
        - docs/modules/**
    - component_id: tool
      name: SDD tool
      paths:
        - sdd/**
